name: Build and Deploy

# Controls when the workflow will run
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Build
      - name: Build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
        run: npm run build
          
      # Deploy to Production branch
      - name: Deploy to production branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages